### PR TITLE
Add Jetbrains sponsor

### PR DESCRIPTION
**Pull request by Qoraiche**
Thanks to Jetbrains provide me with a free os license for all products

@ReeceM please provide me with your email so I can send your license

Thanks for your contributions!

### CODE REVIEW

**Comment by ReeceM** [comment]
Hi there, 

that's awesome that they doing that 👍 :)

email to follow:

**Comment by ReeceM** [comment]
email address is reecestevenmay@gmail.com.

Will delete it after getting the mail 👍

**Comment by Qoraiche** [comment]
> Will delete it after getting the mail 👍

Invitation sent!

**Comment by ReeceM** [comment]
@Qoraiche 💯

**Pull request merged**
