### PR TITLE
Add Laravel 7 Support

### PR DESCRIPTION
**Pull request by blakehooks**

### CODE REVIEW

**Comment by blakehooks** [comment]
> Hi @blakehooks, it would also need the`illuminate\support` made to support 7.0 too then I can merge it 👍
@ReeceM 
Added!

**Comment by ReeceM** [comment]
@blakehooks, awesome and thank you. Once the ci is done I will merge 👍

**Comment by Qoraiche** [comment]
@ReeceM could you create a new PR in maileclipse so we get those changes,

I hope you receive my small donation as well ^^.

**Comment by ReeceM** [comment]
Hi @Qoraiche, looking at the composer file I had locked it to `"reecem/mocker": "1.1.*"`, so it should pick up the new change as I tagged it as `v1.1.3`. 

But I will check to make sure they come through when used 👍 

I did indeed receive the donation, many thanks 😃

**Comment by ReeceM** [comment]
@Qoraiche, I just made a fresh laravel 7 repo and required the maileclipse and it pulled v1.1.3 of mocker with the additions. 

All current and future users should have smooth transition 😃 👍

**Comment by Qoraiche** [comment]
@ReeceM cool 👍

**Pull request merged**
